<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="81787" started-at="2015-10-17T15:22:52Z" finished-at="2015-10-17T15:24:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="81787" started-at="2015-10-17T15:22:52Z" finished-at="2015-10-17T15:24:13Z">
      <class name="autotest.appautotest.testa">
        <test-method status="PASS" signature="setUp()[pri:0, instance:autotest.appautotest.testa@6a5fc7f7]" name="setUp" is-config="true" duration-ms="14227" started-at="2015-10-17T23:22:52Z" finished-at="2015-10-17T23:23:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="login()[pri:0, instance:autotest.appautotest.testa@6a5fc7f7]" name="login" duration-ms="65287" started-at="2015-10-17T23:23:06Z" finished-at="2015-10-17T23:24:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [µÇÂ¼33] but found [µÇÂ¼]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [µÇÂ¼33] but found [µÇÂ¼]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at core.UI.assertEquals(UI.java:46)
	at base.AndroidApp.runTestCase(AndroidApp.java:476)
	at autotest.appautotest.testa.login(testa.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:autotest.appautotest.testa@6a5fc7f7]" name="tearDown" is-config="true" duration-ms="2256" started-at="2015-10-17T23:24:11Z" finished-at="2015-10-17T23:24:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- autotest.appautotest.testa -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
