<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="spring-ma.achievo.com" name="Default test" tests="9" failures="1" timestamp="10 Nov 2015 05:21:17 GMT" time="35.979" errors="0">
  <testcase name="test000login" time="7.55" classname="testTicketWeb.qiChe"/>
  <testcase name="test003login" time="0.001" classname="testTicketWeb.qiChe"/>
  <testcase name="test004login" time="0.001" classname="testTicketWeb.qiChe"/>
  <testcase name="test005login" time="1.428" classname="testTicketWeb.qiChe">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at core.UI.findElement(UI.java:96)
	at core.UI.clear(UI.java:54)
	at testTicketWeb.qiChe.test005login(qiChe.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test005login -->
  <testcase name="test006login" time="0.0" classname="testTicketWeb.qiChe"/>
  <testcase name="test000login" time="5.826" classname="testTicketWeb.baShi"/>
  <testcase name="test002login" time="0.0" classname="testTicketWeb.baShi"/>
  <testcase name="test003login" time="0.001" classname="testTicketWeb.baShi"/>
  <testcase name="test004login" time="0.001" classname="testTicketWeb.baShi"/>
</testsuite> <!-- Default test -->
